import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";
import { generateEncryptionKey } from "@openviktor/shared";

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q: string): Promise<string> =>
	new Promise((res) => rl.question(q, (a) => res(a.trim())));

async function main() {
	console.log("\n  OpenViktor Setup\n");
	console.log("  This wizard will guide you through first-time setup.\n");

	// Check for existing .env
	const envPath = resolve(process.cwd(), ".env");
	if (existsSync(envPath)) {
		const overwrite = await ask("  .env file already exists. Overwrite? (y/N): ");
		if (overwrite.toLowerCase() !== "y") {
			console.log("  Setup cancelled.\n");
			process.exit(0);
		}
	}

	// Step 1: Slack App
	console.log("\n  Step 1: Slack App");
	console.log("  ─────────────────");
	console.log("  Create a Slack app at https://api.slack.com/apps");
	console.log("  Tip: Use the manifest file at slack-app-manifest.yml for one-click setup.\n");

	const botToken = await ask("  Bot Token (xoxb-...): ");
	if (!botToken.startsWith("xoxb-")) {
		console.error("  Error: Bot token must start with xoxb-");
		process.exit(1);
	}

	const appToken = await ask("  App Token (xapp-...): ");
	if (!appToken.startsWith("xapp-")) {
		console.error("  Error: App token must start with xapp-");
		process.exit(1);
	}

	const signingSecret = await ask("  Signing Secret: ");
	if (!signingSecret) {
		console.error("  Error: Signing secret is required");
		process.exit(1);
	}

	// Step 2: LLM
	console.log("\n  Step 2: LLM Provider");
	console.log("  ────────────────────");

	const anthropicKey = await ask("  Anthropic API Key (sk-ant-...): ");
	if (!anthropicKey) {
		console.error("  Error: Anthropic API key is required");
		process.exit(1);
	}

	const openaiKey = await ask("  OpenAI API Key (optional, press Enter to skip): ");
	const googleKey = await ask("  Google AI API Key (optional, press Enter to skip): ");

	// Step 3: Dashboard
	console.log("\n  Step 3: Dashboard");
	console.log("  ─────────────────");

	const dashboardPassword = await ask("  Dashboard password (admin login): ");
	if (!dashboardPassword) {
		console.error("  Error: Dashboard password is required");
		process.exit(1);
	}

	// Step 4: Database
	console.log("\n  Step 4: Database");
	console.log("  ────────────────");

	const dbPassword = (await ask("  PostgreSQL password (default: openviktor): ")) || "openviktor";

	// Generate config
	const encryptionKey = generateEncryptionKey();

	const envContent = [
		"# OpenViktor Configuration",
		"# Generated by setup wizard",
		"",
		"# Deployment",
		"DEPLOYMENT_MODE=selfhosted",
		"",
		"# Slack",
		`SLACK_BOT_TOKEN=${botToken}`,
		`SLACK_APP_TOKEN=${appToken}`,
		`SLACK_SIGNING_SECRET=${signingSecret}`,
		"",
		"# LLM",
		`ANTHROPIC_API_KEY=${anthropicKey}`,
		...(openaiKey ? [`OPENAI_API_KEY=${openaiKey}`] : []),
		...(googleKey ? [`GOOGLE_AI_API_KEY=${googleKey}`] : []),
		"",
		"# Database",
		`DATABASE_URL=postgresql://openviktor:${dbPassword}@localhost:5432/openviktor`,
		`POSTGRES_PASSWORD=${dbPassword}`,
		"",
		"# Redis",
		"REDIS_URL=redis://localhost:6379",
		"",
		"# Dashboard",
		"DASHBOARD_AUTH_MODE=basic",
		"DASHBOARD_USERNAME=admin",
		`DASHBOARD_PASSWORD=${dashboardPassword}`,
		"",
		"# Security",
		`ENCRYPTION_KEY=${encryptionKey}`,
		"",
		"# Application",
		"NODE_ENV=production",
		"LOG_LEVEL=info",
		"",
	].join("\n");

	writeFileSync(envPath, envContent, "utf-8");
	console.log(`\n  .env written to ${envPath}`);

	// Step 5: Start
	console.log("\n  Setup complete!");
	console.log("  ───────────────");
	console.log("  To start OpenViktor:");
	console.log("    docker compose -f docker/docker-compose.selfhosted.yml up -d\n");
	console.log("  Dashboard: http://localhost:3001 (login: admin / your password)\n");

	rl.close();
}

main().catch((err) => {
	console.error("Setup failed:", err.message);
	process.exit(1);
});
